sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t shirink/docker2 -f Dockerfile.dev .

script:
  - docker run -e CI=true shirink/docker2 npm run test
deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "first-app-docker"
  env: "First-app-docker-env"
  bucket_name: "elasticbeanstalk-us-west-1-111180401124"
  bucket_path: "first-app-docker"

  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
