sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t shirink/docker2 -f Dockerfile.dev .

script:
  - docker run -e CI=true shirink/docker2 npm run test
# deploy:
#   provider: elasticbeanstalk
#   region: "us-east-1"
#   app: "my-first-app-docker"
#   env: "My-first-app-docker-env"
#   bucket_name: "my-first-app-docker"
#   bucket_path: "docker"
#   on:
#     branch: main
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY
